### PR TITLE
Add SVG logo

### PR DESCRIPTION
**Pull request by roman01la**
SVG! 😊

### CODE REVIEW

**Comment by martinklepsch** [comment]
The gradient looks a bit different than the rendered PNG but I'll look into that and probably fine tune a bit before merging. Also it will probably render a bit differently due to SVGs flexible nature.

In any case thank you @roman01la, much appreciated 👍

**Comment by roman01la** [comment]
Hmmm... you are right, it's different. I've also tuned letters a bit, so edges are matching pixel grid.

**Comment by martinklepsch** [comment]
Ah thats cool. If we manage to improve the SVG version to a point where
it's identical it might make sense to switch to it as "the source file" as
well.

**Comment by roman01la** [comment]
I've adjusted gradient so it looks better now, not 100% identical though 🙂

**Comment by Deraen** [comment]
Looks near enough for me.

**Pull request merged**
